require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/workouts", type: :request do
  # Workout. As you add validations to Workout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Workout.create! valid_attributes
      get workouts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      workout = Workout.create! valid_attributes
      get workout_url(workout)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_workout_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      workout = Workout.create! valid_attributes
      get edit_workout_url(workout)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Workout" do
        expect {
          post workouts_url, params: {workout: valid_attributes}
        }.to change(Workout, :count).by(1)
      end

      it "redirects to the created workout" do
        post workouts_url, params: {workout: valid_attributes}
        expect(response).to redirect_to(workout_url(Workout.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Workout" do
        expect {
          post workouts_url, params: {workout: invalid_attributes}
        }.to change(Workout, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post workouts_url, params: {workout: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workout" do
        workout = Workout.create! valid_attributes
        patch workout_url(workout), params: {workout: new_attributes}
        workout.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the workout" do
        workout = Workout.create! valid_attributes
        patch workout_url(workout), params: {workout: new_attributes}
        workout.reload
        expect(response).to redirect_to(workout_url(workout))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        workout = Workout.create! valid_attributes
        patch workout_url(workout), params: {workout: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workout" do
      workout = Workout.create! valid_attributes
      expect {
        delete workout_url(workout)
      }.to change(Workout, :count).by(-1)
    end

    it "redirects to the workouts list" do
      workout = Workout.create! valid_attributes
      delete workout_url(workout)
      expect(response).to redirect_to(workouts_url)
    end
  end
end
